/*definition_variables_globales*/
int nbverbe;
int mode;
int temps;
int trouve=0; 
int reflechi = 0;
int position;
int presence_se;
int presence_s;
int n;
int actif=1;
int longueur_terminaison_infinitif;
int longueur_verbe;
int ss_groupe;
int longueur_verbe;
int longueur_radical;
int nombre_fx_verbe=0;
int remarque = 0;
char radical_present[20];
char radical_futur[20];
char radical_subj_present[20];
char radical_passe_simple[20];
char radical[20]="";
char radical_usuel[20]="";
char radical_aux[30]="";
char radical_PG[20];
char participe_passe[20];
char prefixe[20];
char terminaison_infinitif[5];
char conjugue[30]="";
char termin[50] ="";
char mode_string[30];
char temps_string[30];
char verbe_saisi[40];
char *ret;
struct mot tab_caractères_acc[20];
struct verbe verbe;
struct verbe *tabverbes;
struct conjugaison tab_conjugue[6];
struct pronoms pronoms_personnels[6];
struct temps terminaison[11][6];
struct faux_verbe auxil;
struct faux_verbe tab_fx_verbe[100];
struct faux_verbe fx_verbe;
struct mot auxiliaire_present[2][6];
struct mot pronominal[3][6];
